ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp

onlyBuiltDependencies:
  - better-sqlite3
  - electron
  - electron-winstaller

overrides:
  '@types/webpack': ^5

patchedDependencies:
  quasar: patches/quasar.patch
