patchedDependencies:
  quasar: patches/quasar.patch

overrides:
  '@types/node': '^24'
  '@types/webpack': '^5'
  'yauzl': '^3.3.1'

allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  '@parcel/watcher': false
  esbuild: false
  sharp: false
