export const SETTING_IPC_ACTION = Object.freeze({
    GET_SETTING: 'SETTING_IPC_ACTION_GET_SETTING',
    UPDATE_SETTING: 'SETTING_IPC_ACTION_UPDATE_SETTING',
    SHOW_OPEN_DIALOG: 'SETTING_IPC_ACTION_SHOW_OPEN_DIALOG',
})
