export const WINDOW_IPC_ACTION = Object.freeze({
    IS_MAXIMIZED: 'WINDOW_IPC_ACTION_IS_MAXIMIZED',
    CLOSE: 'WINDOW_IPC_ACTION_CLOSE',
    MAXIMIZE: 'WINDOW_IPC_ACTION_MAXIMIZE',
    MINIMIZE: 'WINDOW_IPC_ACTION_MINIMIZE',

    OPEN_GITHUB: 'WINDOW_IPC_ACTION_OPEN_GITHUB',
    OPEN_LOGS_DIR: 'WINDOW_IPC_ACTION_OPEN_LOGS_DIR',
})
