name: Release Build

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn build

      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: CI Build (windows)
          path: dist-package/*.exe

      - name: Update current release
        if: startsWith(github.ref, 'refs/tags/')
        id: update_current
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_prerelease: false

      - name: Upload asset to current release
        if: startsWith(github.ref, 'refs/tags/')
        uses:  Trinovantes/action-release-upload@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.update_current.outputs.release_id }}
          upload_url: ${{ steps.update_current.outputs.upload_url }}
          files: dist-package/*.exe
