name: Release Build

on:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - README.md
      - .vscode
      - .editorconfig
      - .gitignore

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: Trinovantes/action-automatic-release@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_prerelease: false

      - name: Upload assets to release
        uses:  Trinovantes/action-release-upload@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.update_nightly.outputs.release_id }}
          upload_url: ${{ steps.update_nightly.outputs.upload_url }}
          files: |
            ./dist/*.exe
            ./dist/*.zip
            ./dist/*.dmg
            ./dist/*.AppImage
            ./dist/*.snap
            ./dist/*.deb
            ./dist/*.rpm
            ./dist/*.tar.gz
            ./dist/*.yml
            ./dist/*.blockmap
